Server:
  RunMode: debug
  HttpPort: 8082
  ReadTimeout: 60
  WriteTimeout: 60
APP:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 127.0.0.1:33306
  DBName: customs
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30