// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/face_query": {
            "post": {
                "description": "每个字段都可以为空，类似复选框",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "人脸识别结果"
                ],
                "summary": "查询接口",
                "parameters": [
                    {
                        "type": "string",
                        "name": "cameraID",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "timeEnd",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "timeStart",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responseModel.Face"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "responseModel.Face": {
            "type": "object",
            "properties": {
                "cameraID": {
                    "type": "string"
                },
                "faceId": {
                    "type": "integer"
                },
                "faceImgCorrect": {
                    "type": "string"
                },
                "faceImgPredict": {
                    "type": "string"
                },
                "faceTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "172.21.116.147:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "海关项目人脸识别、步态识别、高亢伪接口文档",
	Description:      "第一个版本",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
